# Generated by Django 6.0.5 on 2026-05-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_logentry_boat_alter_logentry_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='boat_model',
            field=models.CharField(blank=True, help_text='Boat model (e.g., Beneteau Oceanis 38.1)', max_length=255),
        ),
        migrations.AddField(
            model_name='boat',
            name='homeport',
            field=models.CharField(blank=True, help_text='Home port / marina', max_length=255),
        ),
        migrations.AddField(
            model_name='boat',
            name='mmsi_registration',
            field=models.CharField(blank=True, help_text='MMSI number or registration ID', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='share_slug',
            field=models.SlugField(blank=True, help_text='Randomized slug for public sharing links', unique=True),
        ),
    ]
